"""ULID generation utilities for event IDs."""

from ulid import ULID
import threading
import time


class MonotonicULIDGenerator:
    """
    Thread-safe monotonic ULID generator.

    Ensures ULIDs are strictly increasing even when generated rapidly
    by tracking the last generated ULID and incrementing if necessary.
    """

    def __init__(self):
        self._lock = threading.Lock()
        self._last_ulid: str | None = None

    def generate(self) -> str:
        """
        Generate a monotonic ULID.

        Returns:
            26-character ULID string that is guaranteed to be greater
            than the previous ULID generated by this instance.
        """
        with self._lock:
            # Generate new ULID
            new_ulid = str(ULID())

            # Ensure monotonicity: if new ULID is not greater than last,
            # wait a tiny bit and regenerate
            while self._last_ulid is not None and new_ulid <= self._last_ulid:
                # Sleep for 1 microsecond to ensure time advances
                time.sleep(0.000001)
                new_ulid = str(ULID())

            self._last_ulid = new_ulid
            return new_ulid


# Global monotonic ULID generator for thread-safe, monotonic ID generation
_monotonic_generator = MonotonicULIDGenerator()


def generate_event_id() -> str:
    """
    Generate ULID for event_id with monotonic guarantees.

    ULIDs are 26-character strings that are:
    - Lexicographically sortable by creation time
    - Globally unique (128-bit entropy)
    - URL-safe (Base32 encoding)
    - Monotonic (strictly increasing even when generated rapidly)

    Returns:
        26-character ULID string
    """
    return _monotonic_generator.generate()


def validate_ulid_format(ulid_str: str) -> bool:
    """
    Validate ULID format (26 chars, alphanumeric).

    Args:
        ulid_str: String to validate

    Returns:
        True if valid ULID format, False otherwise
    """
    if len(ulid_str) != 26:
        return False

    # ULID uses Crockford Base32 (0-9, A-Z excluding I, L, O, U)
    valid_chars = set("0123456789ABCDEFGHJKMNPQRSTVWXYZ")
    return all(c in valid_chars for c in ulid_str.upper())
